# Generated by Django 2.2.11 on 2020-03-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
